name: Cleanup Pull Request

on:
  # https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request_target
  pull_request_target:
    types: [ closed ]
  # https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
    inputs:
      pr:
        description: 'The number of the pull request to cleanup.'
        required: true


jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Show Environment
        run: env | sort
      - name: Show GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  delete-pr-image:
    uses: energy-quants/.github/.github/workflows/cleanup-pr.yml@main
    with:
      org: energy-quants
      repo: mambaforge
      image: mambaforge
      # terniary operator hack: https://github.com/actions/runner/issues/409
      pr:  ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.pr || github.event.number }}
    secrets:
      ghcr_token: ${{ secrets.GHCR_TOKEN }}
