name: Cleanup Pull Request

on:
  # https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request_target
  pull_request_target:
    types: [ closed ]
  # https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
    inputs:
      pr:
        description: 'The number of the pull request to cleanup.'
        required: true


jobs:
  delete-pr-image:
    uses: energy-quants/.github/.github/workflows/cleanup-pr.yml@main
    with:
      org: energy-quants
      repo: mambaforge
      image: mambaforge
      pr:  ${{ github.event.number }}
    secrets:
      ghcr_token: ${{ secrets.GHCR_TOKEN }}
